### ISSUE TITLE
No issue - question about solution

### ISSUE THREAD

**Issue by Faetu** [qewer33/leaf-kde#6]
Hi, this is not a issue, but a question.
how did you solve this problem:
![image](https://user-images.githubusercontent.com/55803495/176738200-8b0b8145-de7f-4513-833c-cf057f648b72.png)

best regards

**Comment by qewer33** [comment]
If I remember correctly it was because the contents was on the root of the aurorae theme archive package, archiving them with parent folder (as such shown in the screenshot below) fixed the problem
![image](https://user-images.githubusercontent.com/69015181/177048593-82533fcd-e299-4f2b-8b70-bae7968fb3a2.png)

**Comment by Faetu** [comment]
nice! Thx for the explanation!
